language: php

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  allow_failures:
    - php: nightly

  include:
    - php: 7.3
      env: PHPCS=1 COVERAGE=0 PHPSTAN=1
    - php: 7.4
      env: PHPCS=1 COVERAGE=1 PHPSTAN=1
    - php: nightly
      env: PHPCS=1 COVERAGE=0 PHPSTAN=1

install:
  - ./bin/phpserv >/dev/null 2>&1 &
  - ./bin/composer validate
  - ./bin/composer install --no-interaction --no-progress --no-suggest
  - mkdir -p build/test-coverage build/test-results
  - ./bin/build app:install CHOWN_USER=$USER,CHGRP_GROUP=$USER,DB_NAME=app,DB_ADMIN_USER=root,DB_USER=root

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script:
  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpcs; fi
  - ./vendor/bin/phpunit --group example --no-coverage
  - if [[ $COVERAGE = 0 ]]; then ./vendor/bin/phpunit --exclude-group example --no-coverage; fi
  - if [[ $COVERAGE = 1 ]]; then ./vendor/bin/phpunit --exclude-group example; fi
  - if [[ $PHPSTAN = 1 ]]; then ./vendor/bin/phpstan analyse; fi

